name: chat_app_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod_auth_client: ^1.1.1
  serverpod_chat_client: ^1.1.1
  serverpod_client: ^1.1.1
